const loader=document.querySelector('.loader');addEventListener('load',()=>setTimeout(()=>loader.classList.add('hide'),900));
const c=document.querySelector('.cursor'),r=document.querySelector('.cursor-ring');addEventListener('mousemove',e=>{if(c){c.style.left=e.clientX+'px';c.style.top=e.clientY+'px';r.style.left=e.clientX+'px';r.style.top=e.clientY+'px'}});
document.querySelectorAll('a,.tilt,.play').forEach(el=>{el.addEventListener('mouseenter',()=>document.body.classList.add('hover'));el.addEventListener('mouseleave',()=>document.body.classList.remove('hover'))});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>io.observe(e));
addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;document.querySelector('.scrollbar').style.width=(scrollY/h*100)+'%'});
// subtle 3D tilt
if(matchMedia('(pointer:fine)').matches){document.querySelectorAll('.tilt').forEach(el=>{el.addEventListener('mousemove',e=>{const q=el.getBoundingClientRect(),x=(e.clientX-q.left)/q.width-.5,y=(e.clientY-q.top)/q.height-.5;el.style.transform=`perspective(900px) rotateX(${(-y*6).toFixed(2)}deg) rotateY(${(x*7).toFixed(2)}deg) translateY(-2px)`});el.addEventListener('mouseleave',()=>el.style.transform='')})}
document.querySelectorAll('.media-card').forEach(card=>{const v=card.querySelector('video'),b=card.querySelector('.play');card.addEventListener('click',()=>{if(v.paused){document.querySelectorAll('.media-card video').forEach(x=>x.pause());v.play();b.textContent='❚❚';card.classList.add('playing')}else{v.pause();b.textContent='▶';card.classList.remove('playing')}});card.addEventListener('mouseenter',()=>v.play().catch(()=>{}));card.addEventListener('mouseleave',()=>{v.pause();v.currentTime=0;b.textContent='▶';card.classList.remove('playing')})});
document.querySelectorAll('.magnetic').forEach(el=>{el.addEventListener('mousemove',e=>{const q=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-q.left-q.width/2)*.08}px,${(e.clientY-q.top-q.height/2)*.08}px)`});el.addEventListener('mouseleave',()=>el.style.transform='')});
